M48
; DRILL file {KiCad 8.0.1-8.0.1-1~ubuntu22.04.1} date 2024-04-07T12:19:45+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-07T12:19:45+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1-8.0.1-1~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X7.25Y-3.025
X8.25Y-3.025
M30
